version: '3.4'

services:
  user_service:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: "123456"
      DB_DATABASE: weather

  db:
    image: mysql:8.0.11
    ports:
      - "13306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "123456"
      MYSQL_DATABASE: weather
      MYSQL_USER: root
      MYSQL_PASSWORD: "123456"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
