svr_config:
  name: "userserver"
  host: "127.0.0.1"
  port: 8000
  user_svr_name: "usersvr"


mysql:
  host: "127.0.0.1"
  port: 3306
  database: "weather"
  username: "root"
  password: "123456"

log:
  level: "debug"
  file_name: "usersvr.log"
  log_path: "../log/usersvr/"
  max_size: 200
  max_age: 30
  max_backups: 7

consul:
  host: "127.0.0.1"
  port: 8500
  tags:
    - "usertsvr"